/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    'payment-methods': PaymentMethod;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'payment-methods': PaymentMethodsSelect<false> | PaymentMethodsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-header': SiteHeader;
  };
  globalsSelect: {
    'site-header': SiteHeaderSelect<false> | SiteHeaderSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Store categories. Assign products to categories from the Products collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Auto-generated from the title when empty. You can edit manually — saving normalizes it to a URL-safe slug.
   */
  slug?: string | null;
  /**
   * Short line shown on the homepage and category page heading.
   */
  subtitle?: string | null;
  /**
   * Long-form SEO copy rendered on the category landing page (below the banner, above the product grid). Use H2/H3 headings, lists and links to build topical depth for the target keyword.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Frequently asked questions shown on the category landing page. Rendered on-page and emitted as FAQPage JSON-LD for rich results.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Create products here, then assign categories so they appear on the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Where the product is listed (homepage sections, search filters). Create categories first under Categories. The "On Sale" category is managed automatically by the On Sale checkbox below.
   */
  category: (number | Category)[];
  /**
   * Auto-generated from the title when empty. You can edit manually — saving normalizes it to a URL-safe slug.
   */
  slug?: string | null;
  /**
   * Price in VND (integer). Example: 150000 displays as 150,000₫.
   */
  price: number;
  /**
   * Tick to put this product on sale. It is added to the "On Sale" category automatically and the storefront shows the reduced price with the original struck through.
   */
  onSale?: boolean | null;
  /**
   * Percentage off the price. Example: 20 turns 150,000₫ into 120,000₫.
   */
  salePercent?: number | null;
  description?: string | null;
  /**
   * When unchecked, the product is hidden from the storefront.
   */
  available?: boolean | null;
  /**
   * Main product photo shown first on the storefront. Replacing it removes the previous main image from the extra gallery automatically.
   */
  image?: (number | null) | Media;
  /**
   * Snapshotted image URL (auto-filled on save). The storefront reads this field.
   */
  storedImage?: {
    url?: string | null;
    alt?: string | null;
    width?: number | null;
    height?: number | null;
    id?: string | null;
  };
  /**
   * Add a row, upload the image, wait for the upload to finish, then save the product once with the main Save button (top-right). Do not save the media drawer separately before saving the product.
   */
  gallery?:
    | {
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Snapshotted gallery URLs — auto-filled when the product is saved.
   */
  storedGallery?:
    | {
        url?: string | null;
        alt?: string | null;
        width?: number | null;
        height?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Multiple variants per product (e.g. color / switch). Leave "Price override" empty to use the main price.
   */
  variants?:
    | {
        /**
         * Label on the variant selector button.
         */
        name: string;
        /**
         * Unique SKU for this variant.
         */
        sku: string;
        /**
         * VND integer. Empty = use the product price.
         */
        priceOverride?: number | null;
        /**
         * Stock for this variant only.
         */
        stock: number;
        /**
         * Optional. When this variant is selected on the storefront, it replaces the main image.
         */
        image?: (number | null) | Media;
        /**
         * Snapshotted variant image URL (auto-filled on save). Keeps images working if the Media file is deleted.
         */
        storedImage?: {
          url?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          id?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment options shown at checkout. Gateway API keys entered here are encrypted before saving and are never sent to the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods".
 */
export interface PaymentMethod {
  id: number;
  /**
   * Stable identifier used in orders and code. Lowercase, no spaces (e.g. cod, bank-transfer, payos). Do not change once orders exist.
   */
  key: string;
  /**
   * Name shown to customers at checkout.
   */
  label: string;
  /**
   * Short helper text shown under the label at checkout.
   */
  description?: string | null;
  /**
   * Uncheck to hide this method from checkout without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * How this method is processed. "Manual transfer" and "Cash" need no API keys; "Gateway" uses a server-configured provider.
   */
  kind: 'cod' | 'manual_transfer' | 'gateway';
  /**
   * Optional icon/logo shown beside the method.
   */
  icon?: (number | null) | Media;
  /**
   * Gateway provider used to process this method.
   */
  provider?: ('payos' | 'stripe' | 'momo' | 'zalopay' | 'vnpay' | 'shopeepay') | null;
  /**
   * API credentials for this gateway. Encrypted before saving — leave credential fields blank when editing to keep existing keys. Register the webhook URL shown in the provider dashboard (see README).
   */
  gatewayCredentials?: {
    /**
     * Indicates whether encrypted credentials are currently stored.
     */
    credentialsConfigured?: boolean | null;
    /**
     * Use sandbox/test endpoints for this gateway (uncheck for production).
     */
    sandboxMode?: boolean | null;
    clientId?: string | null;
    apiKey?: string | null;
    checksumKey?: string | null;
    secretKey?: string | null;
    webhookSecret?: string | null;
    partnerCode?: string | null;
    accessKey?: string | null;
    partnerKey?: string | null;
    merchantExtId?: string | null;
    appId?: string | null;
    key1?: string | null;
    key2?: string | null;
    tmnCode?: string | null;
    hashSecret?: string | null;
    credentialsEnc?: string | null;
  };
  /**
   * Bank account details shown to the customer to complete the transfer.
   */
  transferDetails?: {
    bankName?: string | null;
    accountNumber?: string | null;
    accountHolder?: string | null;
    /**
     * Optional prefix for the transfer content. The order code is always appended automatically.
     */
    transferNote?: string | null;
    /**
     * Static VietQR image customers can scan to pay.
     */
    qrImage?: (number | null) | Media;
  };
  /**
   * Extra instructions shown to the customer after they place the order.
   */
  instructions?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'payment-methods';
        value: number | PaymentMethod;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  content?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  slug?: T;
  price?: T;
  onSale?: T;
  salePercent?: T;
  description?: T;
  available?: T;
  image?: T;
  storedImage?:
    | T
    | {
        url?: T;
        alt?: T;
        width?: T;
        height?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        media?: T;
        id?: T;
      };
  storedGallery?:
    | T
    | {
        url?: T;
        alt?: T;
        width?: T;
        height?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        name?: T;
        sku?: T;
        priceOverride?: T;
        stock?: T;
        image?: T;
        storedImage?:
          | T
          | {
              url?: T;
              alt?: T;
              width?: T;
              height?: T;
              id?: T;
            };
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods_select".
 */
export interface PaymentMethodsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  description?: T;
  enabled?: T;
  sortOrder?: T;
  kind?: T;
  icon?: T;
  provider?: T;
  gatewayCredentials?:
    | T
    | {
        credentialsConfigured?: T;
        sandboxMode?: T;
        clientId?: T;
        apiKey?: T;
        checksumKey?: T;
        secretKey?: T;
        webhookSecret?: T;
        partnerCode?: T;
        accessKey?: T;
        partnerKey?: T;
        merchantExtId?: T;
        appId?: T;
        key1?: T;
        key2?: T;
        tmnCode?: T;
        hashSecret?: T;
        credentialsEnc?: T;
      };
  transferDetails?:
    | T
    | {
        bankName?: T;
        accountNumber?: T;
        accountHolder?: T;
        transferNote?: T;
        qrImage?: T;
      };
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure the announcement banner and navigation tabs on the storefront header. Each tab can be a single link or a multi-category dropdown. Dropdown tabs open on hover.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header".
 */
export interface SiteHeader {
  id: number;
  /**
   * Thin bar shown below the header (e.g. "International Shipping Available"). Turn off to hide.
   */
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    /**
     * Optional. Leave empty for plain text.
     */
    link?: string | null;
    /**
     * Optional hex color. Defaults to white (light) / dark (dark mode).
     */
    backgroundColor?: string | null;
    /**
     * Optional hex color. Defaults to near-black (light) / white (dark mode).
     */
    textColor?: string | null;
  };
  /**
   * Select any built-in tabs you want to remove from the navbar. Leave empty to keep all of them.
   */
  hiddenDefaults?: ('home' | 'shop' | 'categories')[] | null;
  /**
   * Tabs you add here appear alongside the default tabs. Use "Hide default tabs" above to remove any of the built-in ones.
   */
  tabs?:
    | {
        /**
         * Label shown in the storefront navbar.
         */
        label: string;
        /**
         * Tab type. "Dropdown" opens on hover.
         */
        kind: 'home' | 'all-products' | 'category' | 'custom' | 'dropdown';
        /**
         * Links to /search/{category-slug}. Create the category under Categories, then select it here.
         */
        category?: (number | null) | Category;
        /**
         * Use "/" for internal pages or "http(s)://" for external links.
         */
        href?: string | null;
        /**
         * When enabled, the dropdown lists every category automatically. Otherwise add child items below.
         */
        showAllCategories?: boolean | null;
        /**
         * Skip if "List all categories" is enabled above.
         */
        dropdownItems?:
          | {
              /**
               * Leave empty to use the category name.
               */
              label?: string | null;
              category: number | Category;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header_select".
 */
export interface SiteHeaderSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
        backgroundColor?: T;
        textColor?: T;
      };
  hiddenDefaults?: T;
  tabs?:
    | T
    | {
        label?: T;
        kind?: T;
        category?: T;
        href?: T;
        showAllCategories?: T;
        dropdownItems?:
          | T
          | {
              label?: T;
              category?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}