/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    'product-variants': ProductVariant;
    'payment-methods': PaymentMethod;
    carts: Cart;
    orders: Order;
    'content-pages': ContentPage;
    'blog-categories': BlogCategory;
    posts: Post;
    'store-customers': StoreCustomer;
    pages: Page;
    redirects: Redirect;
    exports: Export;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    products: {
      variants: 'product-variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    'payment-methods': PaymentMethodsSelect<false> | PaymentMethodsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'content-pages': ContentPagesSelect<false> | ContentPagesSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'store-customers': StoreCustomersSelect<false> | StoreCustomersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-header': SiteHeader;
    navigation: Navigation;
    'store-settings': StoreSetting;
    'shipping-settings': ShippingSetting;
    'dropship-settings': DropshipSetting;
    'notification-settings': NotificationSetting;
  };
  globalsSelect: {
    'site-header': SiteHeaderSelect<false> | SiteHeaderSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'store-settings': StoreSettingsSelect<false> | StoreSettingsSelect<true>;
    'shipping-settings': ShippingSettingsSelect<false> | ShippingSettingsSelect<true>;
    'dropship-settings': DropshipSettingsSelect<false> | DropshipSettingsSelect<true>;
    'notification-settings': NotificationSettingsSelect<false> | NotificationSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Store categories. Assign products to categories from the Products collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Auto-generated from the title when empty. You can edit manually — saving normalizes it to a URL-safe slug.
   */
  slug?: string | null;
  /**
   * Short line shown on the homepage and category page heading.
   */
  subtitle?: string | null;
  /**
   * Long-form SEO copy rendered on the category landing page (below the banner, above the product grid). Use H2/H3 headings, lists and links to build topical depth for the target keyword.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Frequently asked questions shown on the category landing page. Rendered on-page and emitted as FAQPage JSON-LD for rich results.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Create products here, then assign categories so they appear on the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Where the product is listed (homepage sections, search filters). Create categories first under Categories. The "On Sale" category is managed automatically by the On Sale checkbox below.
   */
  category: (number | Category)[];
  /**
   * Auto-generated from the title when empty. You can edit manually — saving normalizes it to a URL-safe slug.
   */
  slug?: string | null;
  /**
   * Price in VND (integer). Example: 150000 displays as 150,000₫.
   */
  price: number;
  /**
   * Tick to put this product on sale. It is added to the "On Sale" category automatically and the storefront shows the reduced price with the original struck through.
   */
  onSale?: boolean | null;
  /**
   * Percentage off the price. Example: 20 turns 150,000₫ into 120,000₫.
   */
  salePercent?: number | null;
  description?: string | null;
  /**
   * When unchecked, the product is hidden from the storefront.
   */
  available?: boolean | null;
  /**
   * Inventory for products without variants. Leave empty for unlimited stock. Variant products use per-variant stock instead.
   */
  stock?: number | null;
  /**
   * Main product photo shown first on the storefront. Replacing it removes the previous main image from the extra gallery automatically.
   */
  image?: (number | null) | Media;
  /**
   * Snapshotted image URL (auto-filled on save). The storefront reads this field.
   */
  storedImage?: {
    url?: string | null;
    alt?: string | null;
    width?: number | null;
    height?: number | null;
    kind?: ('image' | 'video') | null;
    id?: string | null;
  };
  /**
   * Add a row, pick or upload an image/video, wait until the thumbnail appears, then pause a few seconds before clicking Save. The gallery snapshot updates in the background so the editor stays responsive.
   */
  gallery?:
    | {
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Snapshotted gallery URLs and media type — auto-filled when the product is saved.
   */
  storedGallery?:
    | {
        url?: string | null;
        alt?: string | null;
        width?: number | null;
        height?: number | null;
        kind?: ('image' | 'video') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Save the product first, then use "Create new" to add variants (name, SKU, stock, image). Each variant is linked to this product automatically — no need to pick the product again.
   */
  variants?: {
    docs?: (number | ProductVariant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Managed from each product’s Variants field. Each variant saves on its own so image uploads do not freeze the product editor.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  /**
   * Set automatically when you add a variant from a product page.
   */
  product: number | Product;
  /**
   * Label on the variant selector button.
   */
  name: string;
  /**
   * Unique SKU (global).
   */
  sku: string;
  /**
   * VND integer. Empty = use the product price.
   */
  priceOverride?: number | null;
  /**
   * Stock for this variant only.
   */
  stock: number;
  /**
   * Optional. Shown on the storefront when this variant is selected.
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment options shown at checkout. Gateway API keys entered here are encrypted before saving and are never sent to the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods".
 */
export interface PaymentMethod {
  id: number;
  /**
   * Stable identifier used in orders and code. Lowercase, no spaces (e.g. cod, bank-transfer, payos). Do not change once orders exist.
   */
  key: string;
  /**
   * Name shown to customers at checkout.
   */
  label: string;
  /**
   * Short helper text shown under the label at checkout.
   */
  description?: string | null;
  /**
   * Uncheck to hide this method from checkout without deleting it.
   */
  enabled?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * How this method is processed. "Manual transfer" and "Cash" need no API keys; "Gateway" uses a server-configured provider.
   */
  kind: 'cod' | 'manual_transfer' | 'gateway';
  /**
   * Optional icon/logo shown beside the method.
   */
  icon?: (number | null) | Media;
  /**
   * Gateway provider used to process this method.
   */
  provider?: ('payos' | 'stripe' | 'momo' | 'zalopay' | 'vnpay' | 'shopeepay') | null;
  /**
   * API credentials for this gateway. Encrypted before saving — leave credential fields blank when editing to keep existing keys. Register the webhook URL shown in the provider dashboard (see README).
   */
  gatewayCredentials?: {
    /**
     * Indicates whether encrypted credentials are currently stored.
     */
    credentialsConfigured?: boolean | null;
    /**
     * Use sandbox/test endpoints for this gateway (uncheck for production).
     */
    sandboxMode?: boolean | null;
    clientId?: string | null;
    apiKey?: string | null;
    checksumKey?: string | null;
    secretKey?: string | null;
    webhookSecret?: string | null;
    partnerCode?: string | null;
    accessKey?: string | null;
    partnerKey?: string | null;
    merchantExtId?: string | null;
    appId?: string | null;
    key1?: string | null;
    key2?: string | null;
    tmnCode?: string | null;
    hashSecret?: string | null;
    credentialsEnc?: string | null;
  };
  /**
   * Bank account details shown to the customer to complete the transfer.
   */
  transferDetails?: {
    bankName?: string | null;
    accountNumber?: string | null;
    accountHolder?: string | null;
    /**
     * Optional prefix for the transfer content. The order code is always appended automatically.
     */
    transferNote?: string | null;
    /**
     * Static VietQR image customers can scan to pay.
     */
    qrImage?: (number | null) | Media;
  };
  /**
   * Extra instructions shown to the customer after they place the order.
   */
  instructions?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  sessionId?: string | null;
  customer?: (number | null) | StoreCustomer;
  cartItems?:
    | {
        product: number | Product;
        /**
         * Variant SKU or product id when no variants.
         */
        variantId: string;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  completed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Linked to Prisma User via prismaUserId — not used for CMS admin login.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-customers".
 */
export interface StoreCustomer {
  id: number;
  email: string;
  name?: string | null;
  /**
   * NextAuth / Prisma User.id
   */
  prismaUserId?: string | null;
  phone?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Click an order to open it — use the green panel at the top to confirm & ship. Pending orders: use the "Đánh dấu TT" column.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Numeric order code as string.
   */
  orderId: string;
  /**
   * Total charged (VND).
   */
  totalAmount: number;
  subtotalAmount?: number | null;
  shippingAmount?: number | null;
  discountAmount?: number | null;
  /**
   * VAT/sales tax (VND).
   */
  taxAmount?: number | null;
  /**
   * Amount applied from a gift card (VND).
   */
  giftCardAmount?: number | null;
  couponCode?: string | null;
  /**
   * Gift card code redeemed on this order.
   */
  giftCardCode?: string | null;
  currency: string;
  customer?: (number | null) | StoreCustomer;
  cart?: (number | null) | Cart;
  paymentStatus: 'pending' | 'paid' | 'failed' | 'refunded';
  orderStatus: 'pending' | 'processing' | 'shipped' | 'delivered' | 'canceled';
  deliveryMethod?: ('SHIPMENT' | 'PICKUP') | null;
  paymentMethodKey?: string | null;
  paymentKind?: string | null;
  customerName?: string | null;
  buyerEmail?: string | null;
  phoneNumber?: string | null;
  paymentUrl?: string | null;
  paidAt?: string | null;
  /**
   * When admin confirmed the order for fulfillment.
   */
  confirmedAt?: string | null;
  shippedAt?: string | null;
  deliveredAt?: string | null;
  inventoryAdjusted?: boolean | null;
  lineItems?:
    | {
        productId: string;
        productTitle?: string | null;
        productHandle?: string | null;
        variantSku?: string | null;
        variantName?: string | null;
        quantity: number;
        unitPrice: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: string | null;
  /**
   * Shipping provider handling this order.
   */
  shippingCarrierKey?: ('ghn' | 'ghtk' | 'viettel_post' | 'jt_express' | 'spx' | 'vnpost' | 'other') | null;
  /**
   * Display name (auto-filled from carrier key).
   */
  shippingCarrier?: string | null;
  trackingNumber?: string | null;
  /**
   * Public link for the customer to track shipment.
   */
  trackingUrl?: string | null;
  /**
   * Live carrier tracking status (auto-synced).
   */
  shipmentStatus?:
    | ('awaiting_pickup' | 'picked_up' | 'in_transit' | 'out_for_delivery' | 'delivered' | 'failed')
    | null;
  /**
   * Tracking timeline from the carrier.
   */
  shipmentEvents?:
    | {
        status: 'awaiting_pickup' | 'picked_up' | 'in_transit' | 'out_for_delivery' | 'delivered' | 'failed';
        message: string;
        location?: string | null;
        occurredAt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * prismaUserId, legacy ids, gateway refs.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Marketing/landing pages rendered at /pages/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-pages".
 */
export interface ContentPage {
  id: number;
  title: string;
  slug: string;
  published?: boolean | null;
  layout?:
    | (
        | {
            headline: string;
            subheadline?: string | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            title: string;
            body?: string | null;
            buttonLabel: string;
            buttonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Topics used to organise blog posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  /**
   * URL-safe identifier. Edit manually — saving normalizes it to a slug.
   */
  slug: string;
  description?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts rendered on the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Auto-generated from the title when empty. You can edit manually — saving normalizes it to a URL-safe slug.
   */
  slug?: string | null;
  /**
   * Short summary shown in post listings and meta tags.
   */
  excerpt?: string | null;
  coverImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: (number | null) | User;
  category?: (number | null) | BlogCategory;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Posts are only public once published AND this time has elapsed.
   */
  publishedAt?: string | null;
  status: 'draft' | 'published';
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Custom pages built with the drag-and-drop page builder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Auto-generated from the title when empty. Edit manually to customise the URL.
   */
  slug?: string | null;
  /**
   * Only published pages are visible on the storefront.
   */
  status?: ('draft' | 'published') | null;
  layout?:
    | (
        | HeroBlock
        | FeaturedCollectionBlock
        | FeaturedProductsBlock
        | RichTextBlock
        | ImageWithTextBlock
        | GalleryBlock
        | TestimonialsBlock
        | LogoCloudBlock
        | NewsletterBlock
        | FAQBlock
        | PromoBannerBlock
        | VideoEmbedBlock
        | DividerBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  headline: string;
  subheadline?: string | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  ctaStyle?: ('primary' | 'outline' | 'minimal') | null;
  image?: (number | null) | Media;
  imagePosition?: ('left' | 'right' | 'background' | 'none') | null;
  textAlign?: ('left' | 'center') | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCollectionBlock".
 */
export interface FeaturedCollectionBlock {
  title?: string | null;
  collection: number | Category;
  /**
   * Max number of products to show from this collection.
   */
  limit?: number | null;
  layout?: ('grid' | 'carousel') | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredCollection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductsBlock".
 */
export interface FeaturedProductsBlock {
  title?: string | null;
  products: (number | Product)[];
  layout?: ('grid' | 'carousel') | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredProducts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  textAlign?: ('left' | 'center') | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageWithTextBlock".
 */
export interface ImageWithTextBlock {
  image: number | Media;
  imagePosition?: ('left' | 'right') | null;
  headline: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  imageRatio?: ('1/1' | '4/3' | '3/4' | '16/9') | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageWithText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock".
 */
export interface GalleryBlock {
  title?: string | null;
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  layout?: ('grid' | 'row' | 'bento') | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'gallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  title?: string | null;
  entries: {
    quote: string;
    author: string;
    role?: string | null;
    avatar?: (number | null) | Media;
    rating?: number | null;
    id?: string | null;
  }[];
  layout?: ('grid' | 'single') | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  title?: string | null;
  logos: {
    image: number | Media;
    alt: string;
    href?: string | null;
    id?: string | null;
  }[];
  animate?: boolean | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'logoCloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock".
 */
export interface NewsletterBlock {
  headline: string;
  subheadline?: string | null;
  placeholder?: string | null;
  buttonLabel?: string | null;
  disclaimer?: string | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'newsletter';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock".
 */
export interface FAQBlock {
  title?: string | null;
  items: {
    question: string;
    answer: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  layout?: ('accordion' | 'twoCol') | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBannerBlock".
 */
export interface PromoBannerBlock {
  text: string;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  dismissible?: boolean | null;
  /**
   * Optional expiry date for countdown display.
   */
  countdown?: string | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'promoBanner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock".
 */
export interface VideoEmbedBlock {
  title?: string | null;
  /**
   * YouTube or Vimeo embed URL.
   */
  url: string;
  aspectRatio?: ('16/9' | '4/3' | '1/1') | null;
  /**
   * Optional poster image before playback.
   */
  coverImage?: (number | null) | Media;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock".
 */
export interface DividerBlock {
  style?: ('line' | 'dashed' | 'space' | 'gradient') | null;
  showIcon?: boolean | null;
  /**
   * Background mode for this section.
   */
  background?: ('theme' | 'light' | 'dark' | 'custom') | null;
  /**
   * Hex color, e.g. #f5f0eb.
   */
  backgroundCustom?: string | null;
  /**
   * Max content width for this section.
   */
  containerWidth?: ('narrow' | 'normal' | 'wide' | 'full') | null;
  /**
   * Vertical padding for the section.
   */
  paddingY?: ('compact' | 'base' | 'spacious' | 'none') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'divider';
}
/**
 * Map legacy or retired paths to their new destination. Matched in middleware before authentication.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * The inbound path to match, e.g. /old-product. Normalized to a leading slash with no trailing slash on save.
   */
  from: string;
  /**
   * Destination path (/new-product) or absolute URL (https://…).
   */
  to: string;
  /**
   * 301 is cached by browsers/search engines; 302 is not.
   */
  type: '301' | '302';
  /**
   * Disabled rules are kept for reference but never applied.
   */
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  sort?: string | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'payment-methods';
        value: number | PaymentMethod;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'content-pages';
        value: number | ContentPage;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'store-customers';
        value: number | StoreCustomer;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'exports';
        value: number | Export;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  subtitle?: T;
  content?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  slug?: T;
  price?: T;
  onSale?: T;
  salePercent?: T;
  description?: T;
  available?: T;
  stock?: T;
  image?: T;
  storedImage?:
    | T
    | {
        url?: T;
        alt?: T;
        width?: T;
        height?: T;
        kind?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        media?: T;
        id?: T;
      };
  storedGallery?:
    | T
    | {
        url?: T;
        alt?: T;
        width?: T;
        height?: T;
        kind?: T;
        id?: T;
      };
  variants?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  product?: T;
  name?: T;
  sku?: T;
  priceOverride?: T;
  stock?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payment-methods_select".
 */
export interface PaymentMethodsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  description?: T;
  enabled?: T;
  sortOrder?: T;
  kind?: T;
  icon?: T;
  provider?: T;
  gatewayCredentials?:
    | T
    | {
        credentialsConfigured?: T;
        sandboxMode?: T;
        clientId?: T;
        apiKey?: T;
        checksumKey?: T;
        secretKey?: T;
        webhookSecret?: T;
        partnerCode?: T;
        accessKey?: T;
        partnerKey?: T;
        merchantExtId?: T;
        appId?: T;
        key1?: T;
        key2?: T;
        tmnCode?: T;
        hashSecret?: T;
        credentialsEnc?: T;
      };
  transferDetails?:
    | T
    | {
        bankName?: T;
        accountNumber?: T;
        accountHolder?: T;
        transferNote?: T;
        qrImage?: T;
      };
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  sessionId?: T;
  customer?: T;
  cartItems?:
    | T
    | {
        product?: T;
        variantId?: T;
        quantity?: T;
        id?: T;
      };
  completed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderId?: T;
  totalAmount?: T;
  subtotalAmount?: T;
  shippingAmount?: T;
  discountAmount?: T;
  taxAmount?: T;
  giftCardAmount?: T;
  couponCode?: T;
  giftCardCode?: T;
  currency?: T;
  customer?: T;
  cart?: T;
  paymentStatus?: T;
  orderStatus?: T;
  deliveryMethod?: T;
  paymentMethodKey?: T;
  paymentKind?: T;
  customerName?: T;
  buyerEmail?: T;
  phoneNumber?: T;
  paymentUrl?: T;
  paidAt?: T;
  confirmedAt?: T;
  shippedAt?: T;
  deliveredAt?: T;
  inventoryAdjusted?: T;
  lineItems?:
    | T
    | {
        productId?: T;
        productTitle?: T;
        productHandle?: T;
        variantSku?: T;
        variantName?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  shippingAddress?: T;
  shippingCarrierKey?: T;
  shippingCarrier?: T;
  trackingNumber?: T;
  trackingUrl?: T;
  shipmentStatus?: T;
  shipmentEvents?:
    | T
    | {
        status?: T;
        message?: T;
        location?: T;
        occurredAt?: T;
        id?: T;
      };
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-pages_select".
 */
export interface ContentPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              ctaLabel?: T;
              ctaHref?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  author?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-customers_select".
 */
export interface StoreCustomersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  prismaUserId?: T;
  phone?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        featuredCollection?: T | FeaturedCollectionBlockSelect<T>;
        featuredProducts?: T | FeaturedProductsBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        imageWithText?: T | ImageWithTextBlockSelect<T>;
        gallery?: T | GalleryBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        logoCloud?: T | LogoCloudBlockSelect<T>;
        newsletter?: T | NewsletterBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        promoBanner?: T | PromoBannerBlockSelect<T>;
        videoEmbed?: T | VideoEmbedBlockSelect<T>;
        divider?: T | DividerBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  ctaLabel?: T;
  ctaHref?: T;
  ctaStyle?: T;
  image?: T;
  imagePosition?: T;
  textAlign?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedCollectionBlock_select".
 */
export interface FeaturedCollectionBlockSelect<T extends boolean = true> {
  title?: T;
  collection?: T;
  limit?: T;
  layout?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProductsBlock_select".
 */
export interface FeaturedProductsBlockSelect<T extends boolean = true> {
  title?: T;
  products?: T;
  layout?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  textAlign?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageWithTextBlock_select".
 */
export interface ImageWithTextBlockSelect<T extends boolean = true> {
  image?: T;
  imagePosition?: T;
  headline?: T;
  body?: T;
  ctaLabel?: T;
  ctaHref?: T;
  imageRatio?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryBlock_select".
 */
export interface GalleryBlockSelect<T extends boolean = true> {
  title?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  title?: T;
  entries?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        avatar?: T;
        rating?: T;
        id?: T;
      };
  layout?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  title?: T;
  logos?:
    | T
    | {
        image?: T;
        alt?: T;
        href?: T;
        id?: T;
      };
  animate?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "NewsletterBlock_select".
 */
export interface NewsletterBlockSelect<T extends boolean = true> {
  headline?: T;
  subheadline?: T;
  placeholder?: T;
  buttonLabel?: T;
  disclaimer?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FAQBlock_select".
 */
export interface FAQBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  layout?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PromoBannerBlock_select".
 */
export interface PromoBannerBlockSelect<T extends boolean = true> {
  text?: T;
  ctaLabel?: T;
  ctaHref?: T;
  dismissible?: T;
  countdown?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoEmbedBlock_select".
 */
export interface VideoEmbedBlockSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  aspectRatio?: T;
  coverImage?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DividerBlock_select".
 */
export interface DividerBlockSelect<T extends boolean = true> {
  style?: T;
  showIcon?: T;
  background?: T;
  backgroundCustom?: T;
  containerWidth?: T;
  paddingY?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  sort?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure the announcement banner and navigation tabs on the storefront header. Each tab can be a single link or a multi-category dropdown. Dropdown tabs open on hover.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header".
 */
export interface SiteHeader {
  id: number;
  /**
   * Thin bar shown below the header (e.g. "International Shipping Available"). Turn off to hide.
   */
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    /**
     * Optional. Leave empty for plain text.
     */
    link?: string | null;
    /**
     * Optional hex color. Defaults to white (light) / dark (dark mode).
     */
    backgroundColor?: string | null;
    /**
     * Optional hex color. Defaults to near-black (light) / white (dark mode).
     */
    textColor?: string | null;
  };
  /**
   * When enabled, Home / Shop / Categories appear automatically. Disable this to use only the tabs you add below — deleting a tab then removes it from the navbar.
   */
  includeDefaultTabs?: boolean | null;
  /**
   * Only applies when "Include default tabs" is on. Select built-in tabs to remove from the navbar.
   */
  hiddenDefaults?: ('home' | 'shop' | 'categories')[] | null;
  /**
   * Custom navigation tabs. When "Include default tabs" is off, this list is your complete menu — remove a row and save to delete it from the storefront.
   */
  tabs?:
    | {
        /**
         * Label shown in the storefront navbar.
         */
        label: string;
        /**
         * Tab type. "Dropdown" opens on hover.
         */
        kind: 'home' | 'all-products' | 'category' | 'custom' | 'dropdown';
        /**
         * Links to /search/{category-slug}. Create the category under Categories, then select it here.
         */
        category?: (number | null) | Category;
        /**
         * Use "/" for internal pages or "http(s)://" for external links.
         */
        href?: string | null;
        /**
         * When enabled, the dropdown lists every category automatically. Otherwise add child items below.
         */
        showAllCategories?: boolean | null;
        /**
         * Skip if "List all categories" is enabled above.
         */
        dropdownItems?:
          | {
              /**
               * Leave empty to use the category name.
               */
              label?: string | null;
              category: number | Category;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the footer and mobile-menu link columns. Each column has a heading and a list of links. These are independent of the main site header — leave empty to fall back to the built-in defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Link columns rendered in the storefront footer (e.g. Support, Policies).
   */
  footerMenu?:
    | {
        /**
         * Column heading shown above the links.
         */
        heading: string;
        links?:
          | {
              label: string;
              /**
               * Use "/" for internal pages or "http(s)://" for external links.
               */
              url: string;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Link columns rendered in the slide-out mobile navigation drawer.
   */
  mobileMenu?:
    | {
        /**
         * Column heading shown above the links.
         */
        heading: string;
        links?:
          | {
              label: string;
              /**
               * Use "/" for internal pages or "http(s)://" for external links.
               */
              url: string;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * White-label storefront appearance: logo, colors, fonts, hero, footer, and social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings".
 */
export interface StoreSetting {
  id: number;
  /**
   * Used in navbar, SEO, and hero when no custom hero title is set.
   */
  storeName?: string | null;
  /**
   * Optional line shown under the logo on marketing pages.
   */
  storeSubtitle?: string | null;
  logo?: (number | null) | Media;
  /**
   * Optional. Falls back to main logo with invert filter.
   */
  logoDark?: (number | null) | Media;
  favicon?: (number | null) | Media;
  storeDescription?: string | null;
  /**
   * PWA manifest, welcome toast, and compact UI.
   */
  storeDescriptionShort?: string | null;
  /**
   * Buttons, links, and primary accents (hex).
   */
  primaryColor?: string | null;
  /**
   * Secondary accents, badges, and highlights (hex).
   */
  secondaryColor?: string | null;
  /**
   * Legacy field — use Secondary color instead.
   */
  accentColor?: string | null;
  /**
   * Controls body and heading fonts across the storefront.
   */
  fontPreset?: ('jakarta' | 'inter' | 'roboto' | 'system') | null;
  heroEnabled?: boolean | null;
  /**
   * Small label above the hero title (e.g. "New collection · Free shipping").
   */
  heroEyebrow?: string | null;
  /**
   * Leave empty to use the store name.
   */
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroCtaLabel?: string | null;
  heroCtaUrl?: string | null;
  /**
   * Optional wide banner image behind the hero text.
   */
  heroImage?: (number | null) | Media;
  heroShowCarousel?: boolean | null;
  heroCarouselTitle?: string | null;
  footerTagline?: string | null;
  /**
   * Small uppercase line in the footer (e.g. "Made in Vietnam").
   */
  brandOrigin?: string | null;
  /**
   * Short blurb in the footer about column. Falls back to short store description.
   */
  footerDescription?: string | null;
  /**
   * Optional small print at the bottom (e.g. agency credit).
   */
  footerCredit?: string | null;
  footerShowNewsletter?: boolean | null;
  /**
   * Shown as icon links in the footer. Leave empty to use env defaults.
   */
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  contactAddress?: string | null;
  currencyCode?: string | null;
  checkoutNote?: string | null;
  returnsPolicyUrl?: string | null;
  privacyPolicyUrl?: string | null;
  /**
   * Master switch for the floating Zalo / Messenger chat bubbles.
   */
  chatEnabled?: boolean | null;
  zaloChatEnabled?: boolean | null;
  /**
   * Found in Zalo OA Manager → Settings → OA info.
   */
  zaloOaId?: string | null;
  zaloWelcomeMessage?: string | null;
  messengerChatEnabled?: boolean | null;
  /**
   * Required. You must also whitelist this site domain in the Facebook Page: Inbox → Chat Plugin → Whitelisted Domains, or the bubble will not appear.
   */
  fbPageId?: string | null;
  messengerThemeColor?: string | null;
  messengerGreeting?: string | null;
  taxEnabled?: boolean | null;
  taxRatePercent?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Flat shipping rates, free-shipping threshold, and pickup location for checkout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-settings".
 */
export interface ShippingSetting {
  id: number;
  shipmentEnabled?: boolean | null;
  /**
   * Added to the order total when delivery method is shipment.
   */
  flatRateVnd?: number | null;
  /**
   * 0 = no free-shipping rule. Subtotal is before discount.
   */
  freeShippingThresholdVnd?: number | null;
  pickupEnabled?: boolean | null;
  pickupAddress?: string | null;
  /**
   * Shown on checkout when customer selects pickup.
   */
  pickupInstructions?: string | null;
  /**
   * Optional regional rates. Match keywords against the city/province from the customer address (e.g. "Hồ Chí Minh, HCM, TP.HCM"). Falls back to flat rate when no zone matches.
   */
  zones?:
    | {
        name: string;
        /**
         * Comma-separated city/province keywords to match (case-insensitive).
         */
        regionKeywords: string;
        flatRateVnd?: number | null;
        freeShippingThresholdVnd?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * CJ / dropship stub — set ENABLE_DROPSHIPPING=true to activate runtime.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dropship-settings".
 */
export interface DropshipSetting {
  id: number;
  enabled?: boolean | null;
  provider?: ('cj' | 'manual') | null;
  /**
   * Stored in CMS DB — prefer env vault in production.
   */
  apiKey?: string | null;
  autoSubmitOnPaid?: boolean | null;
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Zalo Official Account notifications sent to the seller when a new order is placed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings".
 */
export interface NotificationSetting {
  id: number;
  zaloEnabled?: boolean | null;
  /**
   * From the Zalo for Developers app dashboard.
   */
  zaloAppId?: string | null;
  zaloAppSecret?: string | null;
  /**
   * The user_id that has chatted with the OA and will receive messages.
   */
  zaloRecipientUserId?: string | null;
  /**
   * Paste the initial refresh token obtained from OA OAuth. Auto-rotated thereafter.
   */
  zaloRefreshToken?: string | null;
  /**
   * Set automatically; do not edit.
   */
  zaloAccessToken?: string | null;
  zaloTokenExpiresAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-header_select".
 */
export interface SiteHeaderSelect<T extends boolean = true> {
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
        backgroundColor?: T;
        textColor?: T;
      };
  includeDefaultTabs?: T;
  hiddenDefaults?: T;
  tabs?:
    | T
    | {
        label?: T;
        kind?: T;
        category?: T;
        href?: T;
        showAllCategories?: T;
        dropdownItems?:
          | T
          | {
              label?: T;
              category?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  footerMenu?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  mobileMenu?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-settings_select".
 */
export interface StoreSettingsSelect<T extends boolean = true> {
  storeName?: T;
  storeSubtitle?: T;
  logo?: T;
  logoDark?: T;
  favicon?: T;
  storeDescription?: T;
  storeDescriptionShort?: T;
  primaryColor?: T;
  secondaryColor?: T;
  accentColor?: T;
  fontPreset?: T;
  heroEnabled?: T;
  heroEyebrow?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  heroCtaLabel?: T;
  heroCtaUrl?: T;
  heroImage?: T;
  heroShowCarousel?: T;
  heroCarouselTitle?: T;
  footerTagline?: T;
  brandOrigin?: T;
  footerDescription?: T;
  footerCredit?: T;
  footerShowNewsletter?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  contactAddress?: T;
  currencyCode?: T;
  checkoutNote?: T;
  returnsPolicyUrl?: T;
  privacyPolicyUrl?: T;
  chatEnabled?: T;
  zaloChatEnabled?: T;
  zaloOaId?: T;
  zaloWelcomeMessage?: T;
  messengerChatEnabled?: T;
  fbPageId?: T;
  messengerThemeColor?: T;
  messengerGreeting?: T;
  taxEnabled?: T;
  taxRatePercent?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-settings_select".
 */
export interface ShippingSettingsSelect<T extends boolean = true> {
  shipmentEnabled?: T;
  flatRateVnd?: T;
  freeShippingThresholdVnd?: T;
  pickupEnabled?: T;
  pickupAddress?: T;
  pickupInstructions?: T;
  zones?:
    | T
    | {
        name?: T;
        regionKeywords?: T;
        flatRateVnd?: T;
        freeShippingThresholdVnd?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dropship-settings_select".
 */
export interface DropshipSettingsSelect<T extends boolean = true> {
  enabled?: T;
  provider?: T;
  apiKey?: T;
  autoSubmitOnPaid?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-settings_select".
 */
export interface NotificationSettingsSelect<T extends boolean = true> {
  zaloEnabled?: T;
  zaloAppId?: T;
  zaloAppSecret?: T;
  zaloRecipientUserId?: T;
  zaloRefreshToken?: T;
  zaloAccessToken?: T;
  zaloTokenExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    name?: string | null;
    format: 'csv' | 'json';
    limit?: number | null;
    sort?: string | null;
    drafts?: ('yes' | 'no') | null;
    selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
    fields?: string[] | null;
    collectionSlug: string;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    user?: string | null;
    userCollection?: string | null;
    exportsCollection?: string | null;
  };
  output: {
    success?: boolean | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}