// app/(payload)/admin/cms/importMap.d.ts
// Type declaration for the file auto-generated by `pnpm payload generate:importmap`.
import type { ImportMap } from 'payload';

export const importMap: ImportMap;
